Attributes = {
	model_condition				: { type: String },
	model_make_id				: { type: String },
	model_make_display			: { type: String },
	model_name					: { type: String },
	model_trim					: { type: String },
	model_year					: { type: Number },
	model_body_style			: { type: String },
	model_engine_position		: { type: String },
	model_engine_cc				: { type: Number },
	model_engine_num_cyl		: { type: Number },
	model_engine_type			: { type: String },
	model_engine_valves_per_cyl	: { type: String },
	model_engine_power_ps		: { type: Number },
	model_engine_power_rpm		: { type: Number },
	model_engine_torque_nm		: { type: Number },
	model_engine_torque_rpm		: { type: Number },
	model_engine_bore_mm		: { type: Number },
	model_engine_stroke_mm		: { type: Number },
	model_engine_compression	: { type: String },
	model_engine_fuel			: { type: String },
	model_top_speed_kph			: { type: Number },
	model_0_to_100_kph			: { type: Number },
	model_drive					: { type: String },
	model_transmission_type		: { type: String },
	model_seats					: { type: Number },
	model_doors					: { type: Number },
	model_weight_kg				: { type: Number },
	model_length_mm				: { type: Number },
	model_width_mm				: { type: Number },
	model_height_mm				: { type: Number },
	model_wheelbase				: { type: Number },
	model_lkm_hwy				: { type: Number },
	model_lkm_mixed				: { type: Number },
	model_lkm_city				: { type: Number },
	model_fuel_cap_l			: { type: Number },
	model_sold_in_us			: { type: Number },
	model_co2					: { type: Number },
	model_vin					: { type: String },
	model_mpg_hwy				: { type: Number },
	model_mpg_city				: { type: Number },
	model_vehicle_style			: { type: String },
	model_transmission_speed	: { type: Number },
	model_vehicle_type_code		: { type: String },
	model_vehicle_category		: { type: String },
	model_interior_color		: { type: String },
	model_exterior_color		: { type: String },
	model_price					: { type: Number },

	//pets
	pet_breed                   : { type: String },
	pet_age                     : { type: String }, // [1, 2, 3, 4, 5]
	pet_age_degree              : { type: String }, // ["baby", "young", "adult", "senior", ]
	pet_size                    : { type: String }, // ["small", "medium", "large"]
	pet_sex                     : { type: String }, // ["male", "femail"]
	pet_description	            : { type: String },
	pet_temperament             : { type: String },
	pet_height       			: { type: String },
	pet_weight					: { type: String },
	pet_care			 		: { type: String },
	pet_living_conditions       : { type: String },
	pet_activity				: { type: String },
	pet_life_expectancy			: { type: String },
	pet_health					: { type: String },
	pet_litter_size			    : { type: String },
	pet_grooming			    : { type: String },
	pet_group			        : { type: String },
	pet_recognition			    : { type: String },
	pet_color   			    : { type: String },
	pet_origin  			    : { type: String },
	pet_coat	  			    : { type: String },
	pet_history					: { type: String },
	pet_senses					: { type: String },
	pet_nutrition				: { type: String },
	pet_habitat                 : { type: String },
	
	// clothing
	model_pattern               : { type: String },
	model_size                  : { type: String },
	model_material              : { type: String },

	owner                       : { type: String }
}

module.exports = Attributes;